#COMPILE EXE
#DIM ALL
#INCLUDE "Win32API.inc"
GLOBAL hDlg AS DWORD
FUNCTION PBMAIN() AS LONG
   DIALOG NEW PIXELS, 0, "Test Code",300,300,250,250, %WS_OVERLAPPEDWINDOW TO hDlg
       CONTROL ADD BUTTON, hDlg, 100,"Push", 10,10,100,25
   DIALOG SHOW MODAL hDlg CALL DlgProc
END FUNCTION
CALLBACK FUNCTION DlgProc() AS LONG
   IF CB.MSG = %WM_COMMAND AND CB.CTL = 100 AND CB.CTLMSG = %BN_CLICKED THEN
       LOCAL i AS LONG
       CONTROL ADD IMAGE, hDlg, 200,"Push", 25,40,5,5, %WS_BORDER
       FOR i = 2 TO 100 STEP 2
         SLEEP 25
         CONTROL SET SIZE hDlg, 200, i, i
         CONTROL REDRAW hDlg, 200
       NEXT i
   END IF
END FUNCTION
